version: '3.7'

services:
  arbiter:
    image: containers.intersystems.com/intersystems/arbiter:2021.1.0.215.0
    init: true
    container_name: mirror-demo-arbiter
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    extra_hosts:
      - "master:172.16.238.20"
      - "backup:172.16.238.30"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN

  master:
    build: .
    image: mirror-demo
    container_name: mirror-demo-master
    networks:
      app_net:
        ipv4_address: 172.16.238.20
      mirror_net:
        ipv4_address: 172.16.220.20
    environment: 
      - IRIS_MIRROR_ROLE=master
    ports:
      - 81:52773
    volumes: 
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
      - ./volume-iris:/certificates
    hostname: master
    extra_hosts:
      - "backup:172.16.238.30"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN
    command: ["-a", "/init_mirror.sh"]

  backup:
    image: mirror-demo
    container_name: mirror-demo-backup
    networks:
      app_net:
        ipv4_address: 172.16.238.30
      mirror_net:
        ipv4_address: 172.16.220.30
    ports:
      - 82:52773
    environment: 
      - IRIS_MIRROR_ROLE=backup
    volumes: 
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
      - ./volume-iris:/certificates
    hostname: backup
    extra_hosts:
      - "master:172.16.238.20"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN
    command: ["-a", "/init_mirror.sh"]

  report:
    image: mirror-demo
    container_name: mirror-demo-report
    networks:
      app_net:
        ipv4_address: 172.16.238.40
      mirror_net:
        ipv4_address: 172.16.220.40
    ports:
      - 83:52773
    environment: 
      - IRIS_MIRROR_ROLE=report
    volumes: 
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
      - ./volume-iris:/certificates
    hostname: report
    extra_hosts:
      - "master:172.16.238.20"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN
    command: ["-a", "/init_mirror.sh"]
  
  webgateway:
    image: tls-ssl-webgateway
    container_name: mirror-demo-webgateway
    networks:
      app_net:
        ipv4_address: 172.16.238.50
    ports:
      # change the local port already used on your system. 
      - "80:80"
      - "443:443"
    environment:
      # IRIS_HOST is setting up with the virtual ip in order to point always on the primary node
      - IRIS_HOST=172.16.238.100
      - IRIS_PORT=1972
      # Replace by the list of ip address allowed to open the CSP system manager
      # https://localhost/csp/bin/RunTime/Module.cxw
      - "SYSTEM_MANAGER=*.*.*.*"
      # the list of web apps
      # /csp allow to the webgateway to redirect all request starting by /csp to the iris instance
      # You can specify a list separate by a space : "IRIS_WEBAPPS=/csp /api /isc /swagger-ui"
      - "IRIS_WEBAPPS=/csp"
    volumes:
      # Mount certificates files.
      - ./volume-apache/webgateway_client.cer:/opt/webgateway/bin/webgateway_client.cer
      - ./volume-apache/webgateway_client.key:/opt/webgateway/bin/webgateway_client.key
      - ./volume-apache/CA_Server.cer:/opt/webgateway/bin/CA_Server.cer
      - ./volume-apache/apache_webgateway.cer:/etc/apache2/certificate/apache_webgateway.cer
      - ./volume-apache/apache_webgateway.key:/etc/apache2/certificate/apache_webgateway.key
    hostname: webgateway
    command: ["--ssl"]
  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  mirror_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.220.0/24"
