version: '3.7'

services:
  arbiter:
    image: containers.intersystems.com/intersystems/arbiter:2021.1.0.215.0
    init: true
    container_name: mirror-demo-arbiter
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    extra_hosts:
      - "master:172.16.238.20"
      - "backup:172.16.238.30"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN

  master:
    build: .
    image: mirror-demo
    container_name: mirror-demo-master
    networks:
      app_net:
        ipv4_address: 172.16.238.20
      mirror_net:
        ipv4_address: 172.16.220.20
    environment: 
      - IRIS_MIRROR_ROLE=master
    ports:
      - 81:52773
    volumes: 
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    hostname: master
    extra_hosts:
      - "backup:172.16.238.30"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN

  backup:
    image: mirror-demo
    container_name: mirror-demo-backup
    networks:
      app_net:
        ipv4_address: 172.16.238.30
      mirror_net:
        ipv4_address: 172.16.220.30
    ports:
      - 82:52773
    environment: 
      - IRIS_MIRROR_ROLE=backup
    volumes: 
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    hostname: backup
    extra_hosts:
      - "master:172.16.238.20"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN

  report:
    image: mirror-demo
    container_name: mirror-demo-report
    networks:
      app_net:
        ipv4_address: 172.16.238.40
      mirror_net:
        ipv4_address: 172.16.220.40
    ports:
      - 83:52773
    environment: 
      - IRIS_MIRROR_ROLE=report
    volumes: 
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    hostname: report
    extra_hosts:
      - "master:172.16.238.20"
      - "report:172.16.238.40"
    cap_add:
      - NET_ADMIN
  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  mirror_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.220.0/24"
